# Generated by Django 4.2.16 on 2026-03-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('speciality', models.CharField(max_length=120)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('hospital', models.CharField(blank=True, max_length=150)),
                ('linkedin_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-experience_years', 'name'],
            },
        ),
    ]
