# Generated by Django 6.0.3 on 2026-03-21 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q8', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='linkedin_url',
        ),
    ]
